<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    '225ac4f132a892d5909550111fa3a942' => $vendorDir . '/alma/alma-php-client/src/lib/array.php',
);
