<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
		<?php foreach ($this->availableInstallmentsCounts() as $n) { ?>
            <p>
                <input
                    type="radio"
                    id="alma-p<?php echo $n ?>x"
                    name="payment[installments_count]"
                    value="<?php echo $n ?>"
					<?php if ($this->defaultInstallmentsCount() === $n) echo "checked" ?>
                >
                <label for="alma-p<?php echo $n ?>x">
					<?php echo $this->__("Pay in %d installments", $n) ?>
                </label>
            </p>
		<?php } ?>
    </li>
</ul>
