<?php
/**
 * 2018 Alma / Nabla SAS
 *
 * THE MIT LICENSE
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
 * to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * @author    Alma / Nabla SAS <contact@getalma.eu>
 * @copyright 2018 Alma / Nabla SAS
 * @license   https://opensource.org/licenses/MIT The MIT License
 *
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $this Alma_Installments_Block_CartWidget */
?>
<?php if ($this->widgetIsEnable()): ?>
    <script src="https://cdn.jsdelivr.net/npm/@alma/widgets@2.x/dist/widgets.umd.js"></script>
    <script>

        /**
         * @description  Wait for end of Dom loading / qty is not load immediately
         */
        window.addEventListener('DOMContentLoaded', () => {
            updateWidget();
        });

        /**
         * @description  Init alma
         */
        var widgets = Alma.Widgets.initialize(
            '<?= $this->getMerchantId() ?>',
            Alma.ApiMode.<?=strtoupper($this->getActiveMode())?>,
        )
        function updateWidget(){
            widgets.add(
                Alma.Widgets.PaymentPlans, {
                    container: '#alma-widget',
                    purchaseAmount: '<?= $this->getFinalPrice() ?>',
                    locale: '<?= $this->getLocale() ?>',
                    plans: <?= $this->getEnableFeePlansForBadge() ?>
                }
            );
        }

    </script>
    <div id="alma-widget"></div>
<?php endif; ?>
